- hosts: localhost
  become: true
  vars_prompt:
  - name: container_name
    prompt: "Enter Container Name"
    private: no
  - name: port
    prompt: "port no"
    private: no

  vars:
  - image_name: "hastivora/sshos:v1"
  tasks:

  - name: "Yum repo for Docker"
    yum_repository:
            name: docker-repo
            description: "Repo for Docker"
            baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
            enabled: yes
            gpgcheck: no

  - name: "Install Docker"
    package:
            name: "docker-ce-18.09.1-3.el7.x86_64"
            state: present

  - name: "Install docker sdk"
    pip:
            name: "docker"

  - name: "Starting Docker Service "
    service:
            name: "docker"
            state: started

  - name: "Pulling Image"
    docker_image:
            name: "{{ image_name }}"
            source: pull

  - name: Launching A Docker Container
    command: docker run -itd --name {{ container_name }} -p {{ port }}:22  {{ image_name  }} 
    register: docker_info

  - debug:
            var: docker_info

  - name: Retrieve IP
    community.general.docker_container_info:
            name: "{{ container_name }}"
    register: ip_info
  - debug:
            var: ip_info.container.NetworkSettings.IPAddress 
  - name: Update Inventory file
    blockinfile:
            path:  /root/taskip.txt
            block: |
                    [docker]
                    "{{ ip_info['container']['NetworkSettings']['IPAddress'] }}" ansible_ssh_user=root ansible_ssh_pass=docker ansible_connection=ssh
    register: g
  - debug:
            var: g.msg
